Update to Turkish translations
chenxiaolong/BCR pull request #188
Opened 2022-12-07 21:30 UTC by EleoXDA

Notification actions

2022-12-07 21:52 UTC, chenxiaolong requested changes

2022-12-07 21:52 UTC, chenxiaolong commented on app/src/main/res/values-ru/strings.xml
> +          <string name="quick_settings_label">Call recording</string>
Looks like there may be a copy/paste issue here with `quick_settings_label` :)

2022-12-07 21:56 UTC, EleoXDA commented on app/src/main/res/values-ru/strings.xml
> +          <string name="quick_settings_label">Call recording</string>
> Looks like there may be a copy/paste issue here with `quick_settings_label` :)

Correct. Will change it

2022-12-08 01:24 UTC, chenxiaolong approved these changes

2022-12-08 01:25 UTC, merged