Update slovak language file
chenxiaolong/BCR pull request #217
Opened 2023-01-10 09:01 UTC by pvagner

Signed-off-by: Peter Vágner <pvdeejay@gmail.com>

2023-01-10 14:04 UTC, Twoomatch requested changes

2023-01-10 14:04 UTC, Twoomatch commented on app/src/main/res/values-sk/strings.xml
> +    <string name="notification_internal_android_error">Nahrávanie zlyhalo: interný komponent systému android (%s). Toto zariadenie pravdepodobne nepodporuje nahrávanie hovorov.</string>
"Android" should be capitalized here.

2023-01-11 11:07 UTC, pvagner commented on app/src/main/res/values-sk/strings.xml
> +    <string name="notification_internal_android_error">Nahrávanie zlyhalo: interný komponent systému android (%s). Toto zariadenie pravdepodobne nepodporuje nahrávanie hovorov.</string>
Thanks for the heads up

2023-01-11 22:57 UTC, chenxiaolong approved these changes

2023-01-11 22:57 UTC, merged