Update Turkish strings.xml
chenxiaolong/BCR pull request #521
Opened 2024-03-30 21:03 UTC by symbuzzer

2024-03-31 17:22 UTC, chenxiaolong requested changes

2024-03-31 17:22 UTC, chenxiaolong commented on app/src/main/res/values-tr/strings.xml
> +    <string name="pref_record_telecom_apps_desc">Android'in telekom sistemiyle entegre olan üçüncü taraf uygulamalardan gelen aramaları kaydedin. Bu aramaların kayıtları büyük ihtimalle sadece sessiz
It looks like the build is failing on this line. I think it's because the `'` needs to be escaped as `\'`.

2024-04-16 20:17 UTC, symbuzzer commented on app/src/main/res/values-tr/strings.xml
> +    <string name="pref_record_telecom_apps_desc">Android'in telekom sistemiyle entegre olan üçüncü taraf uygulamalardan gelen aramaları kaydedin. Bu aramaların kayıtları büyük ihtimalle sadece sessiz
Sorry for delay

2024-04-16 22:36 UTC, chenxiaolong commented on app/src/main/res/values-tr/strings.xml
> +    <string name="pref_record_telecom_apps_desc">Android'in telekom sistemiyle entegre olan üçüncü taraf uygulamalardan gelen aramaları kaydedin. Bu aramaların kayıtları büyük ihtimalle sadece sessiz
No worries!

2024-04-16 22:37 UTC, chenxiaolong approved these changes

2024-04-16 22:37 UTC, merged