Romanian (ro) translate
chenxiaolong/BCR pull request #613
Opened 2024-10-16 13:30 UTC by gilav23

First of all thanks for the app, it is an option for call recording even without root.
I am new to this but want to help to develop the app. I have inserted the translation into the file ‎app/src/main/res/values-ro/strings.xml. I also updated the app/src/main/res/xml/locales_config.xml and app/build.gradle.kts files.
If I got something wrong, let me know.

2024-10-16 23:17 UTC, chenxiaolong requested changes
Thanks for the PR!

I'm not familiar with Romanian, but it looks like the `<plurals>` translations require one for `quantity="few"`. Right now, there are only translations for `quantity="one"` and `quantity="other"`.

```
   /home/runner/work/BCR/BCR/app/src/main/res/values-ro/strings.xml:23: Error: For locale "ro" (Romanian) the following quantity should also be defined: few (e.g. "2 zile") [MissingQuantity]
      <plurals name="pref_min_duration_desc">
```

2024-10-17 08:15 UTC, gilav23 commented on app/src/main/res/values-ro/strings.xml
Sorry if I bother you. I have updated the strings.xml file to resolve the errors.
I wanted to translate everything, now I hope it's good. A good day.

2024-10-17 22:03 UTC, chenxiaolong commented on app/src/main/res/values-ro/strings.xml
It looks like all of the `plurals` sections got removed. Is that what you intended?

I think the proper fix is to add the `few` translations. For example:
```xml
<plurals name="pref_min_duration_desc">
    <item quantity="one">Păstrați înregistrările de cel puțin %d secundă.</item>
    <item quantity="few"> (this is the missing translation) </item>
    <item quantity="other">Păstrați înregistrările de cel puțin %d secunde.</item>
</plurals>
```

2024-10-18 14:42 UTC, gilav23 commented
Thanks for the suggestion.
As I said, I want to translate everything, but I looked at other translations (fr and en), and I didn't find any record with the item "few".
Then I checked other translations where I found the item "few", but only in one string.
Anyway, I updated strings.xml.
A good day.

2024-10-18 14:53 UTC, chenxiaolong commented
> As I said, I want to translate everything, but I looked at other translations (fr and en), and I didn't find any record with the item "few".

Ah, the required items are different depending on the language. Android follows the Unicode rules, which are listed in a (kind of confusing) table here: https://www.unicode.org/cldr/charts/45/supplemental/language_plural_rules.html

Romanian requires `one`, `few`, and `other`:
![image](https://github.com/user-attachments/assets/b3d30ddb-567b-4a15-96a6-cb936976aa28)

(French requires `one`, `many`, and `other`, while English only requires `one` and `other`.)

2024-10-18 17:24 UTC, gilav23 commented
I have removed the item "many", in accordance with the Unicode rules indicated by you.

2024-10-18 23:05 UTC, chenxiaolong approved these changes
Thanks!

2024-10-18 23:05 UTC, merged